# Generated by Django 2.2.7 on 2019-11-26 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='peopleNmEn',
        ),
        migrations.RemoveField(
            model_name='director',
            name='peopleNmEn',
        ),
    ]
