# Generated by Django 2.2.5 on 2019-11-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20191126_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='pubDate',
            field=models.IntegerField(),
        ),
    ]
