# Generated by Django 2.2.7 on 2019-11-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191128_0949'),
        ('accounts', '0002_auto_20191128_0915'),
    ]

    operations = [
    ]
